// AUTO-GENERATED by scripts/copy-sounds-to-public.ts. DO NOT edit by hand.
// Source files: data/sounds/*.mp3 (top-level only). Add or remove there;
// the prebuild/predev hook regenerates this file.
//
// At runtime, focus-shell's audio-ticker picks one URL at random per session
// and loops it after the per-question target — see SPEC §6.12.

const SOUND_BANK_URLS: readonly string[] = [
	"/audio/sounds/boom.mp3",
	"/audio/sounds/bruh.mp3",
	"/audio/sounds/error.mp3",
	"/audio/sounds/faaah.mp3",
	"/audio/sounds/oh-my-god.mp3",
	"/audio/sounds/punch.mp3",
	"/audio/sounds/steve-ouch.mp3",
]

export { SOUND_BANK_URLS }
