#!/usr/bin/env bun

// EXEMPT FROM THE PROJECT RULESET. Native console.log etc.
//
// Copy top-level MP3 files from data/sounds/ into public/audio/sounds/
// AND regenerate src/config/sound-bank.ts with the URL manifest. Runs
// from `bun dev` (predev) and `bun build` (prebuild) — see package.json.
//
// Top-level only: nested subdirectories (data/sounds/success/, etc.)
// are deliberately NOT enumerated. The bank is the top-level *.mp3 files.
// See data/sounds/LICENSE.md for sourcing notes.
//
// The generated src/config/sound-bank.ts is checked into git so the
// dev server has it on first start (avoids a chicken-and-egg where
// importing the manifest in app code would fail before this script
// has run).

import { readdirSync, mkdirSync, copyFileSync, writeFileSync, statSync } from "node:fs"
import { resolve, join, basename } from "node:path"

const projectRoot = resolve(import.meta.dirname, "..")
const sourceDir = join(projectRoot, "data", "sounds")
const publicDir = join(projectRoot, "public", "audio", "sounds")
const manifestPath = join(projectRoot, "src", "config", "sound-bank.ts")

function listTopLevelMp3s(): string[] {
	const entries = readdirSync(sourceDir, { withFileTypes: true })
	const out: string[] = []
	for (const entry of entries) {
		if (entry.isFile() && entry.name.endsWith(".mp3")) {
			out.push(entry.name)
		}
	}
	out.sort()
	return out
}

function copyFiles(filenames: string[]): void {
	mkdirSync(publicDir, { recursive: true })
	for (const name of filenames) {
		const src = join(sourceDir, name)
		const dest = join(publicDir, name)
		copyFileSync(src, dest)
		const sz = statSync(dest).size
		console.log(`  copied ${name} (${sz} bytes)`)
	}
}

function writeManifest(filenames: string[]): void {
	const urls = filenames.map(function toUrl(name) {
		return `/audio/sounds/${basename(name)}`
	})
	const lines: string[] = []
	lines.push("// AUTO-GENERATED by scripts/copy-sounds-to-public.ts. DO NOT edit by hand.")
	lines.push("// Source files: data/sounds/*.mp3 (top-level only). Add or remove there;")
	lines.push("// the prebuild/predev hook regenerates this file.")
	lines.push("//")
	lines.push("// At runtime, focus-shell's audio-ticker picks one URL at random per session")
	lines.push("// and loops it after the per-question target — see SPEC §6.12.")
	lines.push("")
	lines.push("const SOUND_BANK_URLS: readonly string[] = [")
	for (const url of urls) {
		lines.push(`\t"${url}",`)
	}
	lines.push("]")
	lines.push("")
	lines.push("export { SOUND_BANK_URLS }")
	lines.push("")
	writeFileSync(manifestPath, lines.join("\n"))
	console.log(`  wrote ${manifestPath} with ${urls.length} URL(s)`)
}

function main(): void {
	console.log("[copy-sounds-to-public] enumerating data/sounds/*.mp3")
	const filenames = listTopLevelMp3s()
	if (filenames.length === 0) {
		console.warn("[copy-sounds-to-public] WARNING: no top-level *.mp3 files found in data/sounds/")
		console.warn("[copy-sounds-to-public]          The urgency-loop will be silent.")
	}
	console.log(`[copy-sounds-to-public] found ${filenames.length} file(s): ${filenames.join(", ")}`)
	copyFiles(filenames)
	writeManifest(filenames)
	console.log("[copy-sounds-to-public] done")
}

main()
